# Continuous Integration Script
# Deformetrica - ARAMIS

stages:
  - prepare_env   # prepare conda environment defined in environment.yml
  - test    # run unit tests
  - package # package for deployment
  - deploy  # deploy to anaconda cloud
  - cleanup


############
# TEMPLATES
############
.prepare_env_template: &prepare_env
  stage: prepare_env
  script:
    - id
    - pwd
    - ls -al
    - if [ -f "~/.profile" ]; then . ~/.profile; fi
    - conda env create --force --file environment.yml

.test_template: &unit-test
  stage: test
  script:
    - if [ -f "~/.profile" ]; then . ~/.profile; fi
    - source activate deformetrica
    - echo $PYTHONPATH
    - PYTHONPATH=$PYTHONPATH:src/:tests/ ./tests/unit_tests/run_unit_tests.py
    - source deactivate

.test_template: &functional-test
  stage: test
  script:
    - if [ -f "~/.profile" ]; then . ~/.profile; fi
    - source activate deformetrica
    - echo $PYTHONPATH
    - PYTHONPATH=$PYTHONPATH:src/:tests/ ./tests/functional_tests/run_functional_tests.py
    - source deactivate

.package_template: &package
  stage: package
  script:
    - pwd
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.icm-institute.org/aramislab/conda-recipes.git
    - mkdir conda-recipes/deformetrica/build && cd conda-recipes/deformetrica/build
    - conda install conda-build && conda update conda && conda update conda-build
    - export GIT_SSL_NO_VERIFY=1
    - conda-build --py 3.5 --py 3.6 -c pytorch -c anaconda -c conda-forge --output-folder . ../

.deploy:anaconda: &deploy
  stage: deploy
  only:
    - ci
#  only:
#    - tags
#  except:
#    - ^.*dev$
  script:
#    - conda install anaconda-client && conda update anaconda-client
    - pwd
    - cd conda-recipes/deformetrica/build
    - anaconda --token=$ANACONDA_TOKEN upload --user Aramislab --force **/*.tar.bz2

#########
# LINUX
#########
prepare_env:linux:
  <<: *prepare_env
  tags:
    - linux

#unit-test:linux:
#  <<: *unit-test
#  tags:
#    - linux
#    - cuda-cc52
#
#functional-test:linux:
#  <<: *functional-test
#  tags:
#    - linux
#    - cuda-cc52

package:linux:
  <<: *package
  tags:
    - linux
  cache:
    key: "$CI_COMMIT_SHA:linux"
    paths:
      - conda-recipes/deformetrica/build/**/*.tar.bz2

#########
# MACOS
#########
prepare_env:macos:
  <<: *prepare_env
  tags:
    - macos

#unit-test:macos:
#  <<: *unit-test
#  tags:
#    - macos
#
#functional-test:macos:
#  <<: *functional-test
#  tags:
#    - macos

package:macos:
  <<: *package
  tags:
    - macos
  cache:
    key: "$CI_COMMIT_SHA:macos"
    paths:
      - conda-recipes/deformetrica/build/**/*.tar.bz2


###########
# DEPLOY
###########
#deploy:anaconda:test:
#  stage: deploy
#  only:
#    - ^.*dev$
#  script:
#    - conda install anaconda-client && conda update anaconda-client
#    - cd conda-recipes/deformetrica/build
#    - anaconda --token=$ANACONDA_TOKEN upload --user Aramislab --label dev --force **/*.tar.bz2
#  cache:
#    key: "$CI_COMMIT_SHA"
#    paths:
#      - conda-recipes/deformetrica/build

deploy:anaconda:linux:
  <<: *deploy
  tags:
    - linux
  cache:
    key: "$CI_COMMIT_SHA:linux"
    paths:
      - conda-recipes/deformetrica/build

deploy:anaconda:macos:
  <<: *deploy
  tags:
    - linux
  cache:
    key: "$CI_COMMIT_SHA:macos"
    paths:
      - conda-recipes/deformetrica/build

deploy:examples:
  stage: deploy
  tags:
    - linux
  only:
    - ci
#  only:
#    - tags
  script:
    - zip -r examples.zip examples
    - tar -zcvf examples.tar.gz examples
  artifacts:
    name: examples
    paths:
    - examples.zip
    - examples.tar.gz

###########
# CLEANUP
###########
cleanup:linux:
  stage: cleanup
  script:
    - rm -rf conda-recipes/
  cache:
    key: "$CI_COMMIT_SHA:linux"
    paths:
      - conda-recipes/deformetrica/build
  when: always

cleanup:macos:
  stage: cleanup
  script:
    - rm -rf conda-recipes/
  cache:
    key: "$CI_COMMIT_SHA:macos"
    paths:
      - conda-recipes/deformetrica/build
  when: always

###########
# PACKAGE
###########
#package:all:
#  stage: package
#  tags:
#    - linux
#    - install
#  only:
#    - tags
#  script:
#    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.icm-institute.org/aramislab/conda-recipes.git
#    - mkdir conda-recipes/deformetrica/build && cd conda-recipes/deformetrica/build
#    - conda install conda-build anaconda-client
#    - conda update conda
#    - conda update conda-build
#    - export GIT_SSL_NO_VERIFY=1
#    - conda-build --py 3.5 --py 3.6 -c pytorch -c anaconda -c conda-forge --output-folder . ../
#    - conda convert linux-64/*.tar.bz2 -p osx-64 -f
#    - anaconda --token=$ANACONDA_TOKEN upload --user Aramislab --force **/*.tar.bz2
#    - source deactivate
