# Continuous Integration Script
# Deformetrica - ARAMIS
#
stages:
  - build   # build conda environment defined in environment.yml
  - test    # run unit tests
  - package # package for deployment
#  - deploy # deploy on anaconda


############
# TEMPLATES
############
.build_template: &build
  stage: build
  script: conda env create --force --file environment.yml

.test_template: &test
  stage: test
  script:
    - source activate deformetrica
    - pwd
    - ls -al
    - echo $PYTHONPATH
    - PYTHONPATH=$PYTHONPATH:src/:tests/ ./tests/unit_tests/main.py
    - source deactivate


#########
# LINUX
#########
build:linux:
  <<: *build
  tags:
    - linux

test:linux:
  <<: *test
  tags:
    - linux
#    - cuda

#########
# MACOS
#########
build:macos:
  <<: *build
  tags:
    - macos

test:macos:
  <<: *test
  tags:
    - macos

###########
# PACKAGE
###########
package:all:
  stage: package
  tags:
    - linux
  only:
    - master
  script:
    - git clone https://gitlab.icm-institute.org/aramislab/conda-recipes.git
    - mkdir conda-recipes/deformetrica/build
    - conda build -c pytorch -c anaconda -c conda-forge --output-folder conda-recipes/deformetrica/build conda-recipes/deformetrica
    - conda convert conda-recipes/deformetrica/build/linux-64/*.tar.bz2 -p osx-64
    - anaconda --token=$ANACONDA_TOKEN upload --force conda-recipes/deformetrica/build/**/*.tar.bz2
