# Continuous Integration Script
# Deformetrica - ARAMIS

stages:
  - prepare_env   # prepare conda environment defined in environment.yml
  - test    # run unit tests
  - package_and_deploy # package for deployment


############
# TEMPLATES
############
.prepare_env_template: &prepare_env
  stage: prepare_env
  script:
    - id
    - pwd
    - ls -al
    - if [ -f "~/.profile" ]; then . ~/.profile; fi
    - conda env create --force --file environment.yml

.test_template: &unit-test
  stage: test
  script:
    - if [ -f "~/.profile" ]; then . ~/.profile; fi
    - source activate deformetrica
    - echo $PYTHONPATH
    - PYTHONPATH=$PYTHONPATH:src/:tests/ ./tests/unit_tests/run_unit_tests.py
    - source deactivate

.test_template: &functional-test
  stage: test
  script:
    - if [ -f "~/.profile" ]; then . ~/.profile; fi
    - source activate deformetrica
    - echo $PYTHONPATH
    - PYTHONPATH=$PYTHONPATH:src/:tests/ ./tests/functional_tests/run_functional_tests.py
    - source deactivate

.package_and_deploy_template: &package_and_deploy
  stage: package_and_deploy
  only:
    - tags
  script:
    - id && pwd && ls -alh
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.icm-institute.org/aramislab/conda-recipes.git
    - mkdir conda-recipes/deformetrica/build && cd conda-recipes/deformetrica/build
    - conda install conda-build anaconda-client && conda update conda conda-build anaconda-client
    - export GIT_SSL_NO_VERIFY=1
    - conda-build --py 3.5 --py 3.6 -c pytorch -c anaconda -c conda-forge --output-folder . ../
    - anaconda --token=$ANACONDA_TOKEN upload --user Aramislab --force **/*.tar.bz2
    - conda-build purge


#########
# LINUX
#########
prepare_env:linux:
  <<: *prepare_env
  tags:
    - linux

unit-test:linux:
  <<: *unit-test
  tags:
    - linux
    - cuda-cc52

functional-test:linux:
  <<: *functional-test
  tags:
    - linux
    - cuda-cc52

package_and_deploy:linux:
  <<: *package_and_deploy
  tags:
    - linux
    - package

#########
# MACOS
#########
prepare_env:macos:
  <<: *prepare_env
  tags:
    - macos

unit-test:macos:
  <<: *unit-test
  tags:
    - macos

functional-test:macos:
  <<: *functional-test
  tags:
    - macos

package_and_deploy:macos:
  <<: *package_and_deploy
  tags:
    - macos
    - package


###################
# EXAMPLE DATASET
###################
package_and_deploy:examples:
  stage: package_and_deploy
  tags:
    - linux
    - package
  only:
    - tags
  script:
    - zip -r examples.zip examples
    - tar -zcvf examples.tar.gz examples
  artifacts:
    name: examples
    paths:
      - examples.zip
      - examples.tar.gz
