# Continuous Integration Script
# Deformetrica - ARAMIS
#
stages:
  - build   # build conda environment defined in environment.yml
  - test    # run unit tests
  - package # package for deployment
#  - deploy # deploy on anaconda


#########
# LINUX
#########

build:linux:
  stage: build
  tags:
    - linux
  script: conda env create --force --file environment.yml

test:linux:
  stage: test
  tags:
    - linux
#    - cuda
  script:
    - source activate deformetrica
    - pwd
    - ls -al
    - echo $PYTHONPATH
    - PYTHONPATH=$PYTHONPATH:src/:tests/ ./tests/unit_tests/main.py
    - source deactivate

#package:linux:
#  stage: package
#  tags:
#    - linux
#  script:
#    -

#########
# MACOS
#########
build:macos:
  stage: build
  tags:
    - macos
  script: conda env create --force --file environment.yml

test:macos:
  stage: test
  tags:
    - macos
  script:
    - source activate deformetrica
    - pwd
    - ls -al
    - echo $PYTHONPATH
    - PYTHONPATH=$PYTHONPATH:src/:tests/ ./tests/unit_tests/main.py
    - source deactivate

#package:macos:
#  stage: package
#  tags:
#    - linux
#  script:
#    -
