name: deformetrica
channels:
  - intel
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=2.1.1
  - nibabel=2.2.1
  - pillow=5.1.0
  - pytorch=0.4.0
  - torchvision=0.2.1
  - pip:
    - gputil==1.3.0

