name: deformetrica
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.6
  - matplotlib=2.2.2
  - nibabel=2.2.1
  - pillow=5.1.0
  - pytorch=0.4.0
  - torchvision=0.2.1
#  - numpy=1.14.3
#  - cmake=3.11.1d
  - pip
  - pip:
    - gputil==1.3.0
    - pykeops==0.0.10
