name: deformetrica
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python>=3.5
  - matplotlib=2.2.2
  - nibabel=2.3.3
  - pillow=5.1.0
  - pytorch=1.0.1
  - psutil=5.4.8
  - cmake=3.13
  - pip
  - pip:
    - PyQt5>=5.11
    - gputil==1.3.0
    - pykeops==0.1.5
    - sklearn
