name: deformetrica
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.7
  - matplotlib=2.2.2
  - nibabel=2.3.3
  - pillow=5.1.0
  - pytorch=1.0.1
  - vtk==8.2.0
  - psutil=5.4.8
  - ninja=1.9
  - pip
  - pip:
    - PyQt5>=5.11
    - gputil==1.3.0
    - pykeops==1.0
    - cmake>=3.10
    - sklearn
