{% set data = load_setup_py_data() %}

package:
  name: {{ environ.get('PACKAGE_NAME') }}
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: pip install .
  include_recipe: False
  script_env:
    - BUILD_GUI
    - PACKAGE_NAME

requirements:
  build:
    - python {{ python }}
    - setuptools
    - pip
  run:
    - python {{ python }}
    - matplotlib=2.2.2
    - nibabel=2.3.3
    - pillow=5.4.1
    - pytorch=1.0.1
    - psutil=5.4.8
    - vtk=8.2.0

test:
  commands:
    - deformetrica --help

about:
  home: http://www.deformetrica.org
  license: INRIA License
  license_file: LICENSE.txt
  summary: Software for the statistical analysis of 2D and 3D shape data.
